<a href="https://colab.research.google.com/github/chaudhary-dotcom/Python-Beginning-/blob/main/pandasDay1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [40]:
df = pd.read_csv('/Automobile_data (1).csv')
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [41]:
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

In [6]:
df.tail()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [7]:
df = pd.read_csv('/Automobile_data (1).csv', na_values = {
    'price': ['?', 'n.a'],
    'stroke': ['?', 'n.a'],
    'horsepower': ['?', 'n.a'],
    'peak-rpm':['?', 'n.a'],
    'average-mileage': ['?', 'n.a']

})

print(df)

    index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc
1       1  alfa-romero  convertible        88.6   168.8        dohc
2       2  alfa-romero    hatchback        94.5   171.2        ohcv
3       3         audi        sedan        99.8   176.6         ohc
4       4         audi        sedan        99.4   176.6         ohc
..    ...          ...          ...         ...     ...         ...
56     81   volkswagen        sedan        97.3   171.7         ohc
57     82   volkswagen        sedan        97.3   171.7         ohc
58     86   volkswagen        sedan        97.3   171.7         ohc
59     87        volvo        sedan       104.3   188.8         ohc
60     88        volvo        wagon       104.3   188.8         ohc

   num-of-cylinders  horsepower  average-mileage    price
0              four         111               21  13495.0
1              four         111               21  16500.0
2               six         154               19  16500.0
3              four         102               24  13950.0
4              five         115               18  17450.0
..              ...         ...              ...      ...
56             four          85               27   7975.0
57             four          52               37   7995.0
58             four         100               26   9995.0
59             four         114               23  12940.0
60             four         114               23  13415.0

[61 rows x 10 columns]

In [9]:
df.to_csv('/Automobile_data (1).csv')

In [13]:
#find the most expensive car company name
df[['company', 'price']][df.price==df['price'].max()]

          company    price
35  mercedes-benz  45400.0

In [15]:
#print all toyota cars details
car_manufactures = df.groupby('company')
toyotaDf = car_manufactures.get_group('toyota')
toyotaDf

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [18]:
#count total cars per company
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [27]:
#find each company highest price car
car_manufactures = df.groupby('company')
priceDf = car_manufactures[['company','price']].max()
priceDf

                     company    price
company
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

In [28]:
car_manufactures =df.groupby('company')
priceDf = car_manufactures['price'].max()
priceDf

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

In [31]:
#find the average milage of each car making company
car_manufactures = df.groupby('company')
milageDf = car_manufactures['average-mileage'].mean()
milageDf

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64

In [32]:
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [39]:
#sort all cars by price column
carsDf = df.sort_values(by=['price', 'horsepower'], ascending = False)
carsDf.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0

In [45]:
#concatenate two data frames using the following conditions
#create two data frames using following dictionaries
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMW', 'Audi'], 'Price': [23845, 171995, 135925, 71400]}
carDf1 = pd.DataFrame.from_dict(GermanCars)

japneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500, 58900]}
carDf2 = pd.DataFrame.from_dict(japneseCars)

carsDf = pd.concat([carDf1], keys = ['Germany', 'Japnese'])
carsDf

<ipython-input-45-020a65992734>:9: FutureWarning: The behavior of pd.concat with len(keys) != len(objs) is deprecated. In a future version this will raise instead of truncating to the smaller of the two sequences
  carsDf = pd.concat([carDf1], keys = ['Germany', 'Japnese'])

            Company   Price
Germany 0      Ford   23845
        1  Mercedes  171995
        2       BMW  135925
        3      Audi   71400

In [47]:
#concatenate two data frames using the following conditions
#create two data frames using following dictionaries
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMW', 'Audi'], 'Price': [23845, 171995, 135925, 71400]}
carDf1 = pd.DataFrame.from_dict(GermanCars)

japneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price': [29995, 23600, 61500, 58900]}
carDf2 = pd.DataFrame.from_dict(japneseCars)

carsDf = pd.concat([carDf1, carDf2], keys = ['Germany', 'Japnese'])
carsDf

              Company   Price
Germany 0        Ford   23845
        1    Mercedes  171995
        2         BMW  135925
        3        Audi   71400
Japnese 0      Toyota   29995
        1       Honda   23600
        2      Nissan   61500
        3  Mitsubishi   58900

In [53]:
#Merge two data frames and append new data frame as a new column
car_price = {'Company': ['Toyota', 'Honda', 'BMW', 'Audi'], 'Price': [23845, 17995, 135925, 71400]}
carPriceDf = pd.DataFrame.from_dict(car_price)

car_horsepower = {'Company': ['Toyota', 'Honda', 'BMW', 'Audi'], 'horsepower': [141, 80, 182, 160]}
carHorsepowerDf = pd.DataFrame.from_dict(car_horsepower)

carsDf = pd.merge(carPriceDf, carHorsepowerDf, on = 'Company')
carsDf

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMW  135925         182
3    Audi   71400         160

In [6]:
df.head(3)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0

In [7]:
#checking missing values
print(df.isnull().sum())

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [8]:
print(df.isnull().values.any())

True

In [9]:
#finding rows with missing values
print(df[df.isnull().any(axis=1)])

    index  company body-style  wheel-base  length engine-type  \
22     31    isuzu      sedan        94.5   155.9         ohc
23     32    isuzu      sedan        94.5   155.9         ohc
47     63  porsche  hatchback        98.4   175.7       dohcv

   num-of-cylinders  horsepower  average-mileage  price
22             four          70               38    NaN
23             four          70               38    NaN
47            eight         288               17    NaN

In [10]:
df.isnull().sum()

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [22]:
#df.fillna(34, inplace=True)
#print(df.isnull().sum())

In [24]:
priceDf = df.sort_values(by=['price'], ascending = True)
priceDf.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
23,32,isuzu,sedan,94.5,155.9,ohc,four,70,38,34.0
22,31,isuzu,sedan,94.5,155.9,ohc,four,70,38,34.0
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,34.0
13,16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151.0
27,36,mazda,hatchback,93.1,159.1,ohc,four,68,30,5195.0

In [23]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             61 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB

In [35]:
#rename columns with a prefix or suffix
df = df.add_prefix('_')
df = df.add_suffix('_d')
df

,___New_New_New_index_Data_Data_d_d,___New_New_New_company_Data_Data_d_d,___New_New_New_body-style_Data_Data_d_d,___New_New_New_wheel-base_Data_Data_d_d,___New_New_New_length_Data_Data_d_d,___New_New_New_engine-type_Data_Data_d_d,___New_New_New_num-of-cylinders_Data_Data_d_d,___New_New_New_horsepower_Data_Data_d_d,___New_New_New_average-mileage_Data_Data_d_d,___New_New_New_price_Data_Data_d_d
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [42]:
df.iloc[3:7,:]

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0

In [45]:
df.rename(columns=({'wheel-base':'wheel'}), inplace=True)

In [46]:
df.head()

,index,company,body-style,wheel,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0